//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodePrinter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobNumber_PK { get; set; }
        public string JobNumber { get; set; }
        public int Contract_ID { get; set; }
        public string JobTitle { get; set; }
        public System.DateTime DateIssed { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<int> JobAssigned { get; set; }
        public Nullable<int> Client_FK { get; set; }
        public Nullable<int> SubContract_FK { get; set; }
        public Nullable<int> SubJob { get; set; }
        public Nullable<int> PrimaryJobKey { get; set; }
        public Nullable<int> HasSubs { get; set; }
        public Nullable<int> TakenOutBy { get; set; }
        public string ManJobListArray { get; set; }
        public string WorkshopScheduleComments { get; set; }
        public string TargetCostComments { get; set; }
        public Nullable<int> HasTurbineManBatchNumber { get; set; }
        public Nullable<int> ManuPurchaseComplete { get; set; }
        public Nullable<int> StockLeft { get; set; }
        public Nullable<int> BoughtInForStock { get; set; }
        public Nullable<int> PeteBurns { get; set; }
        public string WorkshopScheduleOneNotePageID { get; set; }
    }
}
